export const landingGallery = [
  'https://f004.backblazeb2.com/file/annika-portfolio-public/design/uncomfortable/uncomfortable0.jpg',
  'https://f004.backblazeb2.com/file/annika-portfolio-public/design/industrial_scars/industrialscars15.jpg',
  'https://f004.backblazeb2.com/file/annika-portfolio-public/design/bodynamics/bodynamics9.jpg',
  'https://f004.backblazeb2.com/file/annika-portfolio-public/design/industrial_scars/industrialscars2.jpg',
  'https://f004.backblazeb2.com/file/annika-portfolio-public/design/cornserve/cornserve4.jpg',
  'https://f004.backblazeb2.com/file/annika-portfolio-public/design/datadust2/datadust24.jpg',
  'https://f004.backblazeb2.com/file/annika-portfolio-public/design/dunkleeckenarchiv/dearchive4.png',
  'https://f004.backblazeb2.com/file/annika-portfolio-public/design/forecast/forecast02.jpg',
  'https://f004.backblazeb2.com/file/annika-portfolio-public/design/industrial_scars/industrialscars5.jpg',
  'https://f004.backblazeb2.com/file/annika-portfolio-public/design/industrial_scars/industrialscars1.jpg',
  'https://f004.backblazeb2.com/file/annika-portfolio-public/design/mirage/mirage3.jpg'
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1651779864/Curation/extrasober%20/Extrasober5_mf0he5.jpg',
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1651779279/Curation/dunkleecken/dunkleecken4_ad3di1.jpg'
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1652009913/previewpics/cornserve2_namt4u.jpg',
  //  'https://res.cloudinary.com/dojsjcecs/image/upload/v1652184770/Curation/trashspotting1/trashspotting_poster_yfw6ss.jpg',
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1652007282/previewpics/Bildschirmfoto_2022-05-08_um_14.54.24_sbttqd.png',
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1652007219/previewpics/Bildschirmfoto_2022-05-08_um_14.49.45_fhlgkl.png'
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1652007218/previewpics/zueinander_web12_xnaas8.jpg',
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1651779015/bodynamics/bodynamics1_imxssd.jpg',
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1651779279/Curation/dunkleecken/dunkleecken5_ays99h.jpg',
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1653743911/LandingPageMobile/landingpage10_jcxlrb.jpg',
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1651779624/imperceptible/imperceptible3_zjigh1.jpg',
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1653743911/LandingPageMobile/landingpage13_z36vgl.jpg',
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1653743910/LandingPageMobile/landingpage8_kl67on.jpg',
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1653743910/LandingPageMobile/landingpage7_acbg2u.png',
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1653743910/LandingPageMobile/landingpage4_dwcyu9.jpg',
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1653743911/LandingPageMobile/landingpage12_xrf6qh.jpg',
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1653743910/LandingPageMobile/landingpage2_lv21q8.jpg',
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1653743909/LandingPageMobile/landingpage1_xwczv6.jpg',
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1653743910/LandingPageMobile/landingpage5_cpyodl.jpg',
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1653743909/LandingPageMobile/landingpage3_zcg4gy.jpg',
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1653743909/LandingPageMobile/landingpage6_jb2xpt.jpg',
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1653743911/LandingPageMobile/landingpage15_km572k.jpg',
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1653743912/LandingPageMobile/landingpage17_fwegyq.jpg',
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1653743913/LandingPageMobile/landingpage11_wb03fp.jpg',
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1653743913/LandingPageMobile/landingpage24_q4z0my.jpg',
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1653743915/LandingPageMobile/landingpage21_g6vrz3.jpg',
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1653743915/LandingPageMobile/landingpage33_tslu4y.jpg',
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1653743916/LandingPageMobile/landingpage38_x4gxlq.jpg',
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1653743915/LandingPageMobile/landingpage34_saepdo.jpg',
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1653743916/LandingPageMobile/landingpage35_rbmeek.jpg',
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1653743916/LandingPageMobile/landingpage37_ifgepi.jpg',
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1653743916/LandingPageMobile/landingpage31_gjfrc9.jpg',
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1653743914/LandingPageMobile/landingpage26_iusbfu.jpg',
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1653743912/LandingPageMobile/landingpage19_htenu9.jpg',
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1653743911/LandingPageMobile/landingpage14_fmwlxi.jpg'
];

export const landingGalleryMobile = [
  'https://f004.backblazeb2.com/file/annika-portfolio-public/design/uncomfortable/uncomfortable0.jpg',
  'https://f004.backblazeb2.com/file/annika-portfolio-public/design/industrial_scars/industrialscars15.jpg',
  'https://f004.backblazeb2.com/file/annika-portfolio-public/design/bodynamics/bodynamics9.jpg',
  'https://f004.backblazeb2.com/file/annika-portfolio-public/design/industrial_scars/industrialscars2.jpg',
  'https://f004.backblazeb2.com/file/annika-portfolio-public/design/dunkleeckenarchiv/dearchive4.png',
  'https://f004.backblazeb2.com/file/annika-portfolio-public/landingpage/landingpage18.jpg',
  'https://f004.backblazeb2.com/file/annika-portfolio-public/design/forecast/forecast02.jpg',
  'https://f004.backblazeb2.com/file/annika-portfolio-public/design/industrial_scars/industrialscars5.jpg',
  'https://f004.backblazeb2.com/file/annika-portfolio-public/design/mirage/mirage3.jpg',
  'https://f004.backblazeb2.com/file/annika-portfolio-public/preview/cornserve2.jpg',
  'https://f004.backblazeb2.com/file/annika-portfolio-public/design/imperceptible/imperceptible3.jpg',
  'https://f004.backblazeb2.com/file/annika-portfolio-public/landingpage/landingpage27.jpg',
  'https://f004.backblazeb2.com/file/annika-portfolio-public/landingpage/landingpage30.jpg',
  'https://f004.backblazeb2.com/file/annika-portfolio-public/landingpage/LIlaundpinkaufregend.jpg',
  'https://f004.backblazeb2.com/file/annika-portfolio-public/landingpage/landingpage13.jpg',
  'https://f004.backblazeb2.com/file/annika-portfolio-public/landingpage/landingpage8.jpg',
  'https://f004.backblazeb2.com/file/annika-portfolio-public/landingpage/landingpage7.png',
  'https://f004.backblazeb2.com/file/annika-portfolio-public/landingpage/landingpage12.jpg'
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1653743910/LandingPageMobile/landingpage5.jpg',
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1653743912/LandingPageMobile/landingpage17_fwegyq.jpg',
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1653743913/LandingPageMobile/landingpage11_wb03fp.jpg',
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1653743913/LandingPageMobile/landingpage24_q4z0my.jpg',
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1653743915/LandingPageMobile/landingpage34_saepdo.jpg',
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1653743916/LandingPageMobile/landingpage37_ifgepi.jpg',
  // 'https://res.cloudinary.com/dojsjcecs/image/upload/v1653743916/LandingPageMobile/landingpage31_gjfrc9.jpg'
];
